version: 2
updates:
  - package-ecosystem: pip
    directory: /catalogue
    schedule:
      interval: monthly
    commit-message:
      prefix: "chore(catalogue)"
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
