# ============================================================================
# ICDC / ORAS5
# s3://icdc/healpix/ocean/ORAS5/ORCA/fx/level_*.zarr
# example: s3://icdc/healpix/ocean/ORAS5/ORCA/fx/level_0.zarr/
# ============================================================================

[waterpark-icdc-oras5-ocean]
fs_type = "s3"
root_path = "s3://icdc/healpix/ocean/ORAS5/ORCA/"
drs_format = "waterpark-icdc-oras5-ocean"
glob_pattern = "level_*.zarr"
[waterpark-icdc-oras5-ocean.storage_options]
endpoint_url = "https://s3.waterpark.dkrz.de"
anon = true
[waterpark-icdc-oras5-ocean.defaults]
project = "waterpark"
product = "icdc"
realm = "ocean"
institute = "ecmwf"
model = "nemo3.4.1-lim2"
experiment = "ORAS5"
stac_collection_title = "product|ICDC Satellite Observations (HEALPix)"
stac_collection_description = "product|Satellite remote-sensing climate products curated by the Integrated Climate Data Center (ICDC), University of Hamburg (CERES radiation, GPM/IMERG precipitation, MODIS, ORAS5), remapped to HEALPix and served as Zarr. The thumbnail image comes from https://www.nature.com/articles/s41467-021-23321-7"
stac_collection_documentation_url = "product|https://www.cen.uni-hamburg.de/en/icdc.html"
stac_collection_keywords = "product|remote sensing"
stac_collection_thumbnail_url = "product|https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41467-021-23321-7/MediaObjects/41467_2021_23321_Fig2_HTML.png?as=webp"
stac_collection_thumbnail_type = "product|image/jpeg"
[drs_settings.dialect.waterpark-icdc-oras5-ocean]
sources = ["path", "data"]
[drs_settings.dialect.waterpark-icdc-oras5-ocean.path_specs]
dir_parts = ["time_frequency"]
file_parts = ["_", "level_type"]
[drs_settings.dialect.waterpark-icdc-oras5-ocean.data_specs]
read_kws = { consolidated = true, decode_times = true }
[drs_settings.dialect.waterpark-icdc-oras5-ocean.data_specs.globals]
institute = "institution"
grid_id = "healpix_nside"
grid_label = "healpix_order"
[drs_settings.dialect.waterpark-icdc-oras5-ocean.data_specs.var_attrs.variable]
var = "*"
attr = "short_name"
default = "__name__"
[drs_settings.dialect.waterpark-icdc-oras5-ocean.data_specs.stats.time]
stat = "range"
coords = "time"
default = ["1970-01-01", "1970-01-01"]
