#!/usr/bin/env python3
"""
Turn the runnable examples in ``examples/`` into examples pages.

Each example is a plain Python script that stands entirely on its own. It
imports nothing from this repository, declares its own store URL, saves its
own figure with a plain ``fig.savefig``, and runs with nothing but the
packages in ``examples/requirements.txt``.

That is the property worth protecting, and it is why there is no shared
helper module. A private helper is the worst of both worlds: a library the
reader cannot install but still has to read in order to follow the example
importing it. The few lines that would have lived in one are the lesson in
most cases, so they are repeated inline instead.

The cost of that choice is that the S3 endpoint appears in eight files, so
``--check`` and ``--render`` both verify the ``S3 = {...}`` line is
identical across all of them.

The scripts are literate. ``# %%`` starts a code block, ``# %% [md]`` starts
a prose block written as comments, and ``# %% [figure]`` marks where the
figure goes. The module docstring becomes the page title and its lead. That
is the whole format, and it is the same one Jupytext and Spyder use, so an
example opens as a notebook without conversion.

Two modes, deliberately separate
--------------------------------
``--run`` executes the examples against the live S3 endpoint and writes
their figures into ``assets/examples/``. Those figures are **committed**, for
the same reason the shared pages are vendored rather than fetched: the docs
build then works offline and reproducibly, a changed figure arrives as a
reviewable diff, and the site does not go stale the moment a bucket is
being migrated.

``--render`` only reads the scripts and the committed figures and writes the
markdown. It is pure, fast, and offline, so it runs in every docs build and
an edit to an example's prose reaches the site without anybody running
anything against S3.

The index page is NOT generated. ``data/examples/index.md`` is an ordinary
page, written and edited by hand like every other page on the site, and this
script only substitutes the card grid into it where it finds the marker::

    <!-- examples-cards -->

Everything around the marker is yours. The marker is an HTML comment, so the
source file renders correctly on its own, which means the page can be read on
GitHub and edited in ``make serve`` with live reload. Prefer this shape for
anything else that needs machine-generated content on a human-written page:
a real file with a placeholder beats a page assembled out of string constants
in Python, where the prose is invisible to anyone looking for it.

``--check`` compares the scripts against ``examples.lock`` and reports
figures whose script has changed since they were made. It is the thing to
put in CI: it tells you a figure needs refreshing without needing the
network to find out.

Usage
-----
    python scripts/build_examples.py --render --out .build/data
    python scripts/build_examples.py --run [--only 03] [--continue-on-error]
    python scripts/build_examples.py --check
"""

from __future__ import annotations

import argparse
import hashlib
import os
import re
import shutil
import subprocess
import sys
import tempfile
import textwrap
import tomllib
from dataclasses import dataclass
from pathlib import Path
from typing import List, Optional, Sequence

ROOT = Path(__file__).resolve().parent.parent
EXAMPLES = ROOT / "examples"
FIGURES = ROOT / "assets" / "examples"
LOCK = ROOT / "examples.lock"

#: Pages land here inside the assembled docs tree, not in ``data/``. They are
#: generated, and generated files do not belong in a source directory.
DEFAULT_OUT = ROOT / ".build" / "data"

SECTION = re.compile(r"^#\s*%%\s*(?:\[(?P<kind>\w+)\])?\s*$")

THUMB_WIDTH = 520

#: Replaced by the card grid in the hand-written index page.
CARD_MARKER = "<!-- examples-cards -->"

BANNER = (
    "<!-- Generated by scripts/build_examples.py from examples/{name}.\n"
    "     Edit the example, not this file. -->\n"
)


# --------------------------------------------------------------------------
# parsing
# --------------------------------------------------------------------------
@dataclass
class Block:
    kind: str  # "md", "code" or "figure"
    text: str


@dataclass
class Example:
    path: Path
    title: str
    lead: str
    blocks: List[Block]

    @property
    def stem(self) -> str:
        return self.path.stem

    @property
    def figure(self) -> Path:
        return FIGURES / f"{self.stem}.png"

    def endpoint_line(self) -> Optional[str]:
        """The script's ``S3 = {...}`` line, which must match everywhere."""
        for line in self.path.read_text().splitlines():
            if line.startswith("S3 = {"):
                return line.strip()
        return None

    @property
    def thumbnail(self) -> Path:
        return FIGURES / f"{self.stem}-thumb.png"

    def digest(self) -> str:
        return hashlib.sha256(self.path.read_bytes()).hexdigest()


def split_docstring(source: str) -> tuple[str, str, str]:
    """Return (title, lead, remainder) for a script starting with a docstring."""
    stripped = source.lstrip()
    if not stripped.startswith('"""'):
        raise ValueError("an example must start with a module docstring")

    offset = len(source) - len(stripped)
    end = source.index('"""', offset + 3)
    body = source[offset + 3 : end].strip("\n")
    remainder = source[end + 3 :]

    lines = body.splitlines()
    title = lines[0].strip()
    lead = textwrap.dedent("\n".join(lines[1:])).strip()
    return title, lead, remainder


def uncomment(text: str) -> str:
    """Strip the comment marker from a prose block, keeping indentation."""
    out = []
    for line in text.splitlines():
        if line.startswith("# "):
            out.append(line[2:])
        elif line.strip() == "#":
            out.append("")
        else:
            out.append(line)
    return "\n".join(out).strip("\n")


def parse(path: Path) -> Example:
    title, lead, remainder = split_docstring(path.read_text())

    blocks: List[Block] = []
    kind = "code"
    buffer: List[str] = []

    def flush() -> None:
        text = "\n".join(buffer).strip("\n")
        buffer.clear()
        if kind == "figure":
            blocks.append(Block("figure", ""))
        elif text:
            blocks.append(Block(kind, uncomment(text) if kind == "md" else text))

    for line in remainder.splitlines():
        match = SECTION.match(line)
        if match:
            flush()
            kind = match.group("kind") or "code"
            if kind not in {"md", "code", "figure"}:
                raise ValueError(f"{path.name}: unknown block kind {kind!r}")
            if kind == "figure":
                flush()
                kind = "code"
            continue
        buffer.append(line)
    flush()

    return Example(path=path, title=title, lead=lead, blocks=blocks)


def discover(only: Optional[str] = None) -> List[Example]:
    paths = sorted(p for p in EXAMPLES.glob("[0-9][0-9]_*.py"))
    if only:
        paths = [p for p in paths if p.stem.startswith(only) or only in p.stem]
        if not paths:
            raise SystemExit(f"no example matches {only!r}")
    return [parse(p) for p in paths]


# --------------------------------------------------------------------------
# rendering
# --------------------------------------------------------------------------
def figure_markdown(example: Example, present: bool) -> str:
    if not present:
        # Never fail the docs build over a missing figure. A page without its
        # plot is still a page; a site that will not build is not a site.
        return (
            '!!! warning "Figure not built"\n\n'
            "    This example has not been run against the hub yet. Run\n"
            "    `python scripts/build_examples.py --run` or trigger the\n"
            "    `examples` workflow.\n"
        )
    return (
        f"![{example.title}](../assets/examples/{example.stem}.png)\n"
        f"/// caption\n{example.title}\n///\n"
    )


def render(example: Example, present: bool) -> str:
    parts = [
        BANNER.format(name=example.path.name),
        f"# {example.title}\n",
        f"{example.lead}\n",
    ]

    for block in example.blocks:
        if block.kind == "md":
            parts.append(block.text + "\n")
        elif block.kind == "figure":
            parts.append(figure_markdown(example, present))
        else:
            parts.append(f"```python\n{block.text}\n```\n")

    parts.append(
        "---\n\n"
        f"Run it yourself: [`examples/{example.path.name}`]"
        f"(../assets/examples/{example.path.name})\n"
    )
    return "\n".join(parts)


def render_cards(examples: Sequence[Example]) -> str:
    """The card grid that replaces the marker. Nothing else on the page."""
    cards = []
    for example in examples:
        thumb = (
            f"../assets/examples/{example.thumbnail.name}"
            if example.thumbnail.exists()
            else f"../assets/examples/{example.stem}.png"
        )
        first = example.lead.split("\n\n")[0].replace("\n", " ").strip()
        image = (
            f"[![]({thumb}){{ loading=lazy }}]({example.stem}.md)"
            if example.figure.exists()
            else ""
        )
        cards.append(
            f"-   {image}\n\n"
            f"    **[{example.title}]({example.stem}.md)**\n\n"
            f"    {first}\n"
        )

    return '<div class="grid cards" markdown>\n\n' + "\n".join(cards) + "\n</div>\n"


def inject_cards(examples: Sequence[Example], out: Path) -> None:
    """Substitute the card grid into the hand-written index page.

    The page has already been copied into the build tree by docs-prep. In
    ``make serve`` that copy is a *symlink* back to ``data/examples/index.md``
    (docs-prep uses ``cp -as`` so mkdocs' watcher sees edits), so the file is
    replaced rather than written through: opening it for writing would edit
    the source file in place and commit the generated cards to git.
    """
    page = out / "examples" / "index.md"
    if not page.exists():
        raise SystemExit(
            f"[examples] {page} is missing. The index is a normal page: create "
            f"data/examples/index.md and put {CARD_MARKER} where the cards go."
        )

    text = page.read_text()
    if CARD_MARKER not in text:
        raise SystemExit(
            f"[examples] no {CARD_MARKER} in data/examples/index.md, so there is "
            "nowhere to put the cards. Add the marker on a line of its own."
        )

    rendered = text.replace(CARD_MARKER, render_cards(examples))
    page.unlink()  # never write through the serve symlink
    page.write_text(rendered)


def write_pages(examples: Sequence[Example], out: Path) -> None:
    pages = out / "examples"
    assets = out / "assets" / "examples"
    pages.mkdir(parents=True, exist_ok=True)
    assets.mkdir(parents=True, exist_ok=True)

    for example in examples:
        present = example.figure.exists()
        (pages / f"{example.stem}.md").write_text(render(example, present))
        # The page offers the script as a download, so it has to be reachable
        # as a static file rather than only as a code block.
        shutil.copy2(example.path, assets / example.path.name)
        if not present:
            print(f"[examples] no figure for {example.stem}, page written anyway")

    shutil.copy2(EXAMPLES / "requirements.txt", assets / "requirements.txt")

    inject_cards(examples, out)
    print(f"[examples] wrote {len(examples)} pages to {pages}")


# --------------------------------------------------------------------------
# running
# --------------------------------------------------------------------------
def make_thumbnail(figure: Path, target: Path) -> None:
    try:
        from PIL import Image
    except ImportError:  # pragma: no cover
        print("[examples] pillow missing, skipping thumbnails")
        return

    with Image.open(figure) as image:
        scale = THUMB_WIDTH / image.width
        size = (THUMB_WIDTH, max(1, round(image.height * scale)))
        image.convert("RGB").resize(size, Image.LANCZOS).save(target, optimize=True)


def run(examples: Sequence[Example], keep_going: bool) -> int:
    FIGURES.mkdir(parents=True, exist_ok=True)

    environment = dict(os.environ)
    environment["MPLBACKEND"] = "Agg"

    entries: dict[str, dict[str, str]] = {}
    failures = 0

    for example in examples:
        print(f"[examples] running {example.path.name}", flush=True)

        # In a scratch directory, so the script can write its figure with a
        # plain relative savefig the way a reader would, while the harness
        # still decides where it ends up.
        with tempfile.TemporaryDirectory(prefix="examples-") as scratch:
            shutil.copy2(example.path, Path(scratch) / example.path.name)
            result = subprocess.run(
                [sys.executable, example.path.name],
                cwd=scratch,
                env=environment,
            )
            produced = sorted(Path(scratch).glob("*.png"))

            if result.returncode != 0:
                failures += 1
                print(f"[examples] {example.path.name} failed", file=sys.stderr)
                if not keep_going:
                    return 1
                continue

            if len(produced) != 1:
                failures += 1
                print(
                    f"[examples] {example.path.name} wrote {len(produced)} PNGs, "
                    "expected exactly one",
                    file=sys.stderr,
                )
                if not keep_going:
                    return 1
                continue

            shutil.copy2(produced[0], example.figure)

        make_thumbnail(example.figure, example.thumbnail)
        entries[example.path.name] = {
            "script": example.digest(),
            "figure": hashlib.sha256(example.figure.read_bytes()).hexdigest(),
        }

    write_lock(entries)
    return 1 if failures else 0


def check_endpoints(examples: Sequence[Example]) -> List[str]:
    """Every example must name the same S3 endpoint, since none share code."""
    seen: dict[str, List[str]] = {}
    for example in examples:
        line = example.endpoint_line()
        if line is None:
            seen.setdefault("<missing>", []).append(example.path.name)
        else:
            seen.setdefault(line, []).append(example.path.name)

    if len(seen) <= 1:
        return []

    majority = max(seen, key=lambda key: len(seen[key]))
    problems = [f"endpoints disagree; most say {majority}"]
    for line, names in seen.items():
        if line != majority:
            problems.append(f"  {', '.join(names)}: {line}")
    return problems


def write_lock(entries: dict[str, dict[str, str]]) -> None:
    """Merge into the existing lock, so ``--only`` does not orphan the rest."""
    existing = read_lock()
    existing.update(entries)

    lines = [
        "# Generated by scripts/build_examples.py. Do not edit.",
        "#",
        "# Hash of each example as it was when its figure was made, so --check",
        "# can spot a figure that no longer matches its script without going",
        "# to the network.",
        "",
    ]
    for name in sorted(existing):
        lines.append(f"[examples.{name.replace('.', '_')}]")
        lines.append(f'file = "{name}"')
        lines.append(f'script = "{existing[name]["script"]}"')
        lines.append(f'figure = "{existing[name]["figure"]}"')
        lines.append("")
    LOCK.write_text("\n".join(lines))
    print(f"[examples] updated {LOCK.name}")


def read_lock() -> dict[str, dict[str, str]]:
    if not LOCK.exists():
        return {}
    with LOCK.open("rb") as handle:
        data = tomllib.load(handle)
    return {entry["file"]: entry for entry in data.get("examples", {}).values()}


def check(examples: Sequence[Example]) -> int:
    lock = read_lock()
    stale: List[str] = []

    for example in examples:
        recorded = lock.get(example.path.name)
        if recorded is None:
            stale.append(f"{example.path.name}: never run")
        elif recorded["script"] != example.digest():
            stale.append(f"{example.path.name}: changed since its figure was made")
        elif not example.figure.exists():
            stale.append(f"{example.path.name}: figure missing from assets/examples/")

    for name in sorted(set(lock) - {e.path.name for e in examples}):
        stale.append(f"{name}: in the lock but no longer in examples/")

    stale.extend(check_endpoints(examples))

    if not stale:
        print(f"[examples] {len(examples)} examples, all figures current")
        return 0

    print("[examples] figures need refreshing:", file=sys.stderr)
    for line in stale:
        print(f"  {line}", file=sys.stderr)
    print(
        "\nRun `python scripts/build_examples.py --run`, or trigger the "
        "`examples` workflow from the Actions tab.",
        file=sys.stderr,
    )
    return 1


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--render", action="store_true", help="write the pages")
    mode.add_argument("--run", action="store_true", help="execute the examples")
    mode.add_argument("--check", action="store_true", help="report stale figures")
    parser.add_argument(
        "--out",
        type=Path,
        default=DEFAULT_OUT,
        help="assembled docs tree (default: .build/data)",
    )
    parser.add_argument("--only", help="restrict to examples matching this")
    parser.add_argument(
        "--continue-on-error",
        action="store_true",
        help="keep going when an example fails",
    )
    args = parser.parse_args()

    examples = discover(args.only)

    if args.render:
        if not args.out.exists():
            raise SystemExit(
                f"[examples] {args.out} does not exist. This runs after the docs "
                "tree is assembled; use tox rather than calling it directly."
            )
        write_pages(examples, args.out)
        return 0

    if args.run:
        return run(examples, args.continue_on_error)

    return check(examples)


if __name__ == "__main__":
    sys.exit(main())
