#!/usr/bin/env python3
"""
Vendor the shared documentation pages from an upstream repository.

Some pages are rendered by both this site and the grid-doctor technical
site. Rather than keeping two copies in sync by hand, upstream owns them
and this script copies them in at a pinned commit.

The copies are committed to this repository on purpose. That keeps the
docs build offline and reproducible, makes upstream changes visible as a
normal diff in a pull request, and means a contributor can clone and build
without any extra setup. The price is that the pin has to be bumped, which
is what ``--update`` and the sync-shared workflow are for.

Usage
-----
    python scripts/sync_shared.py            # restore files to the pin
    python scripts/sync_shared.py --check    # fail if they were edited here
    python scripts/sync_shared.py --update   # bump the pin to upstream tip

``--check`` is offline: it compares the files on disk against the hashes in
shared.lock, which is written whenever they are synced. That makes it cheap
enough for a commit hook, and it tells a hand edit apart from a sync,
because a sync updates the lock in the same breath.

``--check --remote`` does the slower thing and compares against upstream
itself, which also catches a lock file edited to match a tampered page.
Everything else needs the network.
"""

from __future__ import annotations

import argparse
import hashlib
import io
import subprocess
import sys
import tarfile
import tomllib
import urllib.request
from pathlib import Path
from typing import Dict, Optional

ROOT = Path(__file__).resolve().parent.parent
SOURCES = ROOT / "shared-sources.toml"
# Machine-written, committed alongside the vendored files. Separate from
# shared-sources.toml so the hand-edited pin and the generated hashes never
# fight over the same file.
LOCK = ROOT / "shared.lock"

HEADER = (
    "<!-- Vendored from {repo}@{short} ({src}).\n"
    "     Do not edit here: changes belong upstream and will be overwritten\n"
    "     by scripts/sync_shared.py. -->\n"
)


def load_sources() -> dict:
    with SOURCES.open("rb") as handle:
        return tomllib.load(handle)


def resolve_ref(repo: str, ref: str) -> str:
    """Resolve a branch or tag name to a commit sha via ls-remote."""
    url = f"https://github.com/{repo}.git"
    for candidate in (f"refs/heads/{ref}", f"refs/tags/{ref}^{{}}", ref):
        out = subprocess.run(
            ["git", "ls-remote", url, candidate],
            capture_output=True,
            text=True,
            check=True,
        ).stdout.strip()
        if out:
            return out.split()[0]
    raise SystemExit(f"could not resolve {ref!r} in {repo}")


def fetch_tree(repo: str, sha: str) -> Dict[str, bytes]:
    """Download a repo tarball at `sha` and return {path: bytes}."""
    url = f"https://codeload.github.com/{repo}/tar.gz/{sha}"
    with urllib.request.urlopen(url) as response:
        blob = response.read()

    files: Dict[str, bytes] = {}
    with tarfile.open(fileobj=io.BytesIO(blob), mode="r:gz") as tar:
        for member in tar.getmembers():
            if not member.isfile():
                continue
            # Strip the "<repo>-<sha>/" prefix GitHub adds.
            _, _, path = member.name.partition("/")
            handle = tar.extractfile(member)
            if handle is not None:
                files[path] = handle.read()
    return files


def digest(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def read_lock() -> dict:
    """Hashes of the vendored files as of the last sync."""
    if not LOCK.is_file():
        return {}
    try:
        with LOCK.open("rb") as handle:
            return tomllib.load(handle)
    except (tomllib.TOMLDecodeError, OSError):
        return {}


def write_lock(name: str, sha: str, hashes: Dict[str, str]) -> None:
    """Record what was written, so --check needs no network."""
    lock = read_lock()
    lock[name] = {"commit": sha, "files": dict(sorted(hashes.items()))}

    lines = [
        "# Generated by scripts/sync_shared.py. Do not edit.",
        "#",
        "# Hashes of the vendored files as they were written, so --check can",
        "# tell a hand edit from a sync without going to the network.",
        "",
    ]
    for source, entry in sorted(lock.items()):
        lines.append(f"[{source}]")
        lines.append(f'commit = "{entry["commit"]}"')
        lines.append("")
        lines.append(f"[{source}.files]")
        for rel, checksum in entry["files"].items():
            lines.append(f'"{rel}" = "{checksum}"')
        lines.append("")
    LOCK.write_text("\n".join(lines), encoding="utf-8")


def check_offline(name: str, cfg: dict) -> bool:
    """Compare the files on disk with the lock. True when they differ."""
    lock = read_lock().get(name)
    dest = ROOT / cfg["target_dir"]

    if not lock:
        print(
            f"  no lock entry for [{name}]. Run the script once to create it."
        )
        return True

    if lock["commit"] != cfg["commit"]:
        print(
            f"  pinned at {cfg['commit'][:8]} but last synced "
            f"{lock['commit'][:8]}; run the script to catch up"
        )
        return True

    expected = lock["files"]
    changed = False

    for rel, checksum in sorted(expected.items()):
        target = dest / rel
        if not target.is_file():
            print(f"  {cfg['target_dir']}/{rel}: missing")
            changed = True
        elif digest(target.read_bytes()) != checksum:
            print(f"  {cfg['target_dir']}/{rel}: edited here")
            changed = True

    for stray in sorted(dest.rglob("*")):
        if stray.is_file() and str(stray.relative_to(dest)) not in expected:
            print(f"  {cfg['target_dir']}/{stray.relative_to(dest)}: not upstream")
            changed = True

    return changed


def strip_header(text: str) -> str:
    """Remove a previously injected provenance header."""
    if text.startswith("<!-- Vendored from "):
        _, _, rest = text.partition("-->\n")
        return rest.lstrip("\n")
    return text


def sync_source(
    name: str,
    cfg: dict,
    sha: Optional[str],
    check_only: bool,
) -> tuple[bool, str]:
    """Materialise one source. Returns (changed, resolved_sha)."""
    repo = cfg["repo"]
    src_dir = cfg["source_dir"].rstrip("/")
    dest = ROOT / cfg["target_dir"]
    sha = sha or cfg["commit"]

    wanted = {}
    remote = fetch_tree(repo, sha)
    prefix = src_dir + "/"
    for path, data in remote.items():
        if path.startswith(prefix):
            wanted[path[len(prefix) :]] = data

    if not wanted:
        raise SystemExit(f"[{name}] {src_dir} is empty at {sha[:8]} in {repo}")

    include = cfg.get("include")
    if include:
        missing = sorted(set(include) - set(wanted))
        if missing:
            raise SystemExit(f"[{name}] missing upstream: {', '.join(missing)}")
        wanted = {k: v for k, v in wanted.items() if k in include}

    changed = False
    hashes: Dict[str, str] = {}
    dest.mkdir(parents=True, exist_ok=True)

    for rel, data in sorted(wanted.items()):
        target = dest / rel
        body = data.decode("utf-8")
        if rel.endswith(".md"):
            body = HEADER.format(
                repo=repo, short=sha[:8], src=f"{src_dir}/{rel}"
            ) + "\n" + strip_header(body)
        new = body.encode("utf-8")
        hashes[rel] = digest(new)

        current = target.read_bytes() if target.is_file() else None
        if current == new:
            continue
        changed = True
        if check_only:
            state = "differs from pin" if current is not None else "missing"
            print(f"  {cfg['target_dir']}/{rel}: {state}")
            continue
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(new)
        print(f"  wrote {cfg['target_dir']}/{rel}")

    # Files that upstream removed should go too, otherwise a deleted page
    # lingers forever and the nav keeps pointing at it.
    for stray in sorted(dest.rglob("*")):
        if stray.is_file() and str(stray.relative_to(dest)) not in wanted:
            changed = True
            if check_only:
                print(f"  {cfg['target_dir']}/{stray.relative_to(dest)}: not upstream")
            else:
                stray.unlink()
                print(f"  removed {cfg['target_dir']}/{stray.relative_to(dest)}")

    if not check_only:
        write_lock(name, sha, hashes)

    return changed, sha


def write_pin(name: str, sha: str) -> None:
    """Rewrite just the commit line for one source, preserving comments."""
    text = SOURCES.read_text(encoding="utf-8")
    lines = text.splitlines(keepends=True)
    in_section = False
    for index, line in enumerate(lines):
        stripped = line.strip()
        if stripped.startswith("["):
            in_section = stripped in (f"[{name}]", f"[source.{name}]")
        elif in_section and stripped.startswith("commit"):
            indent = line[: len(line) - len(line.lstrip())]
            lines[index] = f'{indent}commit = "{sha}"\n'
            SOURCES.write_text("".join(lines), encoding="utf-8")
            return
    raise SystemExit(f"no commit key found for [{name}] in {SOURCES.name}")


def main(argv: Optional[list[str]] = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="Report local edits and exit non-zero, without writing. "
        "Offline: compares against shared.lock.",
    )
    parser.add_argument(
        "--remote",
        action="store_true",
        help="With --check, compare against upstream instead of the lock.",
    )
    parser.add_argument(
        "--update",
        nargs="?",
        const="",
        metavar="REF",
        help="Re-pin to the tip of REF (default: the configured ref) and sync.",
    )
    parser.add_argument(
        "--source",
        action="append",
        help="Limit to one named source. Repeatable.",
    )
    args = parser.parse_args(argv)

    sources = load_sources().get("source", {})
    if not sources:
        raise SystemExit(f"no [source.*] entries in {SOURCES.name}")

    any_change = False
    for name, cfg in sources.items():
        if args.source and name not in args.source:
            continue
        print(f"[{name}] {cfg['repo']}:{cfg['source_dir']}")

        sha = None
        if args.update is not None:
            ref = args.update or cfg.get("ref", "main")
            sha = resolve_ref(cfg["repo"], ref)
            if sha == cfg["commit"]:
                print(f"  already at {sha[:8]} ({ref})")
            else:
                print(f"  {cfg['commit'][:8]} -> {sha[:8]} ({ref})")

        if args.check and not args.remote and args.update is None:
            changed = check_offline(name, cfg)
            resolved = cfg["commit"]
        else:
            changed, resolved = sync_source(name, cfg, sha, args.check)
        any_change = any_change or changed

        if args.update is not None and not args.check:
            write_pin(name, resolved)

        if not changed:
            print(f"  up to date at {resolved[:8]}")

    if args.check and any_change:
        print(
            "\nThe vendored shared docs differ from what was synced.\n"
            "These pages are owned by grid-doctor: fix them upstream, then\n"
            "`python scripts/sync_shared.py --update`. To discard a local\n"
            "edit, `python scripts/sync_shared.py` restores them.",
            file=sys.stderr,
        )
        return 1
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
